version: '3'

services:
  app:
    container_name: bot
    build: .
    env_file:
      - .env
    depends_on:
      - tracker_db
    links:
      - tracker_db
    restart: unless-stopped
  tracker_db:
    container_name: tracker_db
    image: postgres:16-alpine
    restart: on-failure
    ports:
      - "${DB_PORT}:5432"
    env_file:
      - .env
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - db_volume:/var/lib/postgresql/data

volumes:
  db_volume: